version: '3.7'

services:
  backend:
    image: steveimm/trackme:latest
    depends_on:
      - mongodb
      - redis
      - influxdb
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"

  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - db-mongo:/data/db

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  influxdb:
    image: influxdb
    restart: unless-stopped
    env_file: .env
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: $INFLUX_USERNAME
      DOCKER_INFLUXDB_INIT_PASSWORD: $INFLUX_PASSWORD
      DOCKER_INFLUXDB_INIT_ORG: $INFLUX_ORG
      DOCKER_INFLUXDB_INIT_BUCKET: $INFLUX_BUCKET
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: $INFLUX_TOKEN
    ports:
      - 8086:8086
    volumes:
      - db-influx:/var/lib/influxdb2

volumes:
  db-mongo:
  db-influx:
