version: '3.7'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - 27017:27017

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6378:6379
