name: Build and Deploy

on:
  push:
    branches: [ master, configure-workflow ]
  pull_request:
    branches: [ master ]
    
jobs:
  push-to-registry:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - run: echo $DOCKER_USERNAME $DOCKER_TOKEN
    - name: Login Docker
      uses: docker/login-action@v1.12.0
      with:
        username: $DOCKER_USERNAME
        password: $DOCKER_TOKEN
    - name: Build image and push to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 
          steveimm/trackme:latest
